docfx/doc/cake-npm.md

Improve documentation regarding Cake.Npm addin

Improve documentation regarding Cake.Npm addin

---

ReleaseNotes.md
src/Cake.Npm.Module.Tests/Cake.Npm.Module.Tests.csproj
src/Cake.Npm.Module/Cake.Npm.Module.csproj
tools/Modules/packages.config
tools/packages.config

Also updated  Cake.Testing to 0.33.0 and the local cake version (for building) to 0.34.1

Updated Cake.Core to 0.33.0

---

ReleaseNotes.md
src/Cake.Npm.Module.Tests/NpmPackageInstallerFixture.cs
src/Cake.Npm.Module.Tests/NpmPackageInstallerTests.cs
src/Cake.Npm.Module/NpmPackageInstaller.cs

(GH-9) using IToolLocator to get the correct npm executable

---

docfx/doc/cake-npm.md
docfx/doc/install.md

a `tools/Modules/packages.config`-file to adding `#module`-directive in the cake file

(GH-12) switched in installation-documentation from manually creating

---

src/Cake.Npm.Module.Tests/Cake.Npm.Module.Tests.csproj
src/Cake.Npm.Module.Tests/NpmPackageInstallerFixture.cs
src/Cake.Npm.Module.Tests/NpmPackageInstallerTests.cs
src/Cake.Npm.Module/Cake.Npm.Module.csproj
src/Cake.Npm.Module/Constants.cs
src/Cake.Npm.Module/Extensions.cs
src/Cake.Npm.Module/NpmContentResolver.cs
src/Cake.Npm.Module/NpmPackageInstaller.cs

also implemented or suppressed all suggestions.
fixes #18

(GH-18) removed all warnings from build

---

src/.editorconfig
src/Cake.Npm.Module.Tests/NpmPackageInstallerTests.cs
src/Cake.Npm.Module.sln
src/Cake.Npm.Module/Cake.Npm.Module.csproj
src/Cake.Npm.Module/Extensions.cs
src/Cake.Npm.Module/INpmContentResolver.cs
src/Cake.Npm.Module/NpmContentResolver.cs
src/Cake.Npm.Module/NpmModule.cs
src/Cake.Npm.Module/NpmPackageInstaller.cs
src/stylecop.json

and stylecop, then fixed all warnings (mostly indentation/formatting and
comments).
fixes #19

(GH-19) added references to CakeContrib.Guidelines

---

.github/dependabot.yml
.github/workflows/build.yml

up-to-date and build.yml to add builds using GitHub-Actions.
Addresses most of #22

(GH-22) added dependabot.yml to keep dependencies

---

.github/dependabot-cake.yml
recipe.cake

Also added a scheduled workflow to auto-update cake dependencies
using the dependabot-cake action.

(maint)  updated cake.recipe to version 2.1.0

---

docs/input/_Bottom.cshtml
docs/input/assets/css/override.less

with a link to GitHub discussions
fixes #36

(GH-36) replaced link to Gitter

---

src/Cake.Npm.Module.Tests/Cake.Npm.Module.Tests.csproj
src/Cake.Npm.Module/Cake.Npm.Module.csproj

(GH-40) bumped Cake references to Cake 1.0.0

---

src/Cake.Npm.Module/Cake.Npm.Module.csproj

(GH-42) Remove net461 target, leaving only netstandard2.0

---

src/Cake.Npm.Module/Cake.Npm.Module.csproj

(GH-49) added cake-module tag

---

GitReleaseManager.yaml

(GH-50) updated GRM config

---

GitReleaseManager.yaml

(GH-55) fixed NuGet link in GRM config

---

src/Cake.Npm.Module/Cake.Npm.Module.csproj

(GH-58) updated CCG

---

.github/workflows/codeql-analysis.yml

(GH-60) fixed codeql-analysis

---

src/Cake.Npm.Module/Cake.Npm.Module.csproj

this will also update the logo and fix #64

(GH-64) updated CakeContrib.Guidelines

---

src/Cake.Npm.Module/Cake.Npm.Module.csproj

Fixes #79 
Added the settings in project file to include readme-file in nupkg

Include readme in nupkg

---

src/Cake.Npm.Module.Tests/Cake.Npm.Module.Tests.csproj
src/Cake.Npm.Module/Cake.Npm.Module.csproj

and CakeContrib.Guidelines to 1.3.0
fixes #92

(#92) Bumped Cake to 2.0.0

---

.config/dotnet-tools.json
.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
build.ps1
build.sh
recipe.cake
src/Cake.Npm.Module.Tests/Cake.Npm.Module.Tests.csproj
src/Cake.Npm.Module/Cake.Npm.Module.csproj

(GH-117) Bump Cake references to 3.0.0

---

.github/renovate.json
.github/workflows/build.yml
.github/workflows/codeql-analysis.yml

and switched renovate config to cake-contrib/renovate-presets

(maint) bump GitHub CI machines

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
demo/frosting/build/Build.csproj
demo/script/.config/dotnet-tools.json
global.json
src/Cake.Npm.Module.Tests/Cake.Npm.Module.Tests.csproj
src/Cake.Npm.Module/Cake.Npm.Module.csproj

and CakeContrib.Guidelines to 1.5.1
fixes #174

(#174) Update Cake.Core to 4.0.0

---

recipe.cake

(#224) disable codecov

---

.github/workflows/build.yml

(#289) update macos-12 runner to macos-13

---

recipe.cake

(#293) bump GRM to 0.18.0
